en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Company Name. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Devil's Avocado"
  description: ""
  showHeader: false
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: ""
